spring:
  application:
    name: VisionHive

  datasource:
    url: jdbc:sqlserver://${AZURE_SQL_SERVER}:1433;database=${AZURE_SQL_DB};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: ${AZURE_SQL_USER}
    password: ${AZURE_SQL_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    br.com.fiap: DEBUG