spring:
  application:
    name: VisionHive

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB_NAME}?sslmode=require
    username: ${POSTGRES_ADMIN_USER}
    password: ${POSTGRES_ADMIN_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.temp.use_jdbc_metadata_defaults: false

  flyway:
    enabled: true

logging:
  level:
    br.com.fiap: DEBUG