spring:
  application:
    name: VisionHive

  datasource:
    url: jdbc:oracle:thin:@//oracle.fiap.com.br:1521/ORCL
    username: ${USUARIO_ORACLE}
    password: ${SENHA_ORACLE}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect

  flyway:
    enabled: false

  data:
    mongodb:
      uri: mongodb://localhost:27017/visionhive
      database: visionhive

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    br.com.fiap: DEBUG